# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bmservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bmservice.proto',
  package='RPCBitmap',
  syntax='proto3',
  serialized_options=_b('\n\030lv.jing.taichi.webB\tRPCBitmapP\000'),
  serialized_pb=_b('\n\x0f\x62mservice.proto\x12\tRPCBitmap\".\n\rBitmapRequest\x12\x0f\n\x07\x62izname\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\x85\x01\n\x0b\x42itmapReply\x12\x10\n\x08highbits\x18\x01 \x01(\x05\x12\x34\n\x07\x62itmaps\x18\x02 \x03(\x0b\x32#.RPCBitmap.BitmapReply.BitmapsEntry\x1a.\n\x0c\x42itmapsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32M\n\nPostBitmap\x12?\n\tgetBitmap\x12\x18.RPCBitmap.BitmapRequest\x1a\x16.RPCBitmap.BitmapReply\"\x00\x42\'\n\x18\x63lv.jing.taichi.webB\tRPCBitmapP\x00\x62\x06proto3')
)




_BITMAPREQUEST = _descriptor.Descriptor(
  name='BitmapRequest',
  full_name='RPCBitmap.BitmapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bizname', full_name='RPCBitmap.BitmapRequest.bizname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='RPCBitmap.BitmapRequest.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=76,
)


_BITMAPREPLY_BITMAPSENTRY = _descriptor.Descriptor(
  name='BitmapsEntry',
  full_name='RPCBitmap.BitmapReply.BitmapsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RPCBitmap.BitmapReply.BitmapsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='RPCBitmap.BitmapReply.BitmapsEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=212,
)

_BITMAPREPLY = _descriptor.Descriptor(
  name='BitmapReply',
  full_name='RPCBitmap.BitmapReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='highbits', full_name='RPCBitmap.BitmapReply.highbits', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitmaps', full_name='RPCBitmap.BitmapReply.bitmaps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BITMAPREPLY_BITMAPSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=212,
)

_BITMAPREPLY_BITMAPSENTRY.containing_type = _BITMAPREPLY
_BITMAPREPLY.fields_by_name['bitmaps'].message_type = _BITMAPREPLY_BITMAPSENTRY
DESCRIPTOR.message_types_by_name['BitmapRequest'] = _BITMAPREQUEST
DESCRIPTOR.message_types_by_name['BitmapReply'] = _BITMAPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitmapRequest = _reflection.GeneratedProtocolMessageType('BitmapRequest', (_message.Message,), dict(
  DESCRIPTOR = _BITMAPREQUEST,
  __module__ = 'bmservice_pb2'
  # @@protoc_insertion_point(class_scope:RPCBitmap.BitmapRequest)
  ))
_sym_db.RegisterMessage(BitmapRequest)

BitmapReply = _reflection.GeneratedProtocolMessageType('BitmapReply', (_message.Message,), dict(

  BitmapsEntry = _reflection.GeneratedProtocolMessageType('BitmapsEntry', (_message.Message,), dict(
    DESCRIPTOR = _BITMAPREPLY_BITMAPSENTRY,
    __module__ = 'bmservice_pb2'
    # @@protoc_insertion_point(class_scope:RPCBitmap.BitmapReply.BitmapsEntry)
    ))
  ,
  DESCRIPTOR = _BITMAPREPLY,
  __module__ = 'bmservice_pb2'
  # @@protoc_insertion_point(class_scope:RPCBitmap.BitmapReply)
  ))
_sym_db.RegisterMessage(BitmapReply)
_sym_db.RegisterMessage(BitmapReply.BitmapsEntry)


DESCRIPTOR._options = None
_BITMAPREPLY_BITMAPSENTRY._options = None

_POSTBITMAP = _descriptor.ServiceDescriptor(
  name='PostBitmap',
  full_name='RPCBitmap.PostBitmap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=214,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='getBitmap',
    full_name='RPCBitmap.PostBitmap.getBitmap',
    index=0,
    containing_service=None,
    input_type=_BITMAPREQUEST,
    output_type=_BITMAPREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTBITMAP)

DESCRIPTOR.services_by_name['PostBitmap'] = _POSTBITMAP

# @@protoc_insertion_point(module_scope)
